version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: unimate-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-unimate}
      MYSQL_USER: ${MYSQL_USER:-unimate_admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin123}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: