spring:
  datasource:
    url: ${TEST_DB_URL:${DB_URL:jdbc:mysql://127.0.0.1:3306/unimate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${TEST_DB_USERNAME:${DB_USERNAME:unimate_admin}}
    password: ${TEST_DB_PASSWORD:${DB_PASSWORD:admin123}}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false

logging:
  level:
    root: INFO
